[package]
name = "yozefu"
description = "yozefu is a CLI tool for Apache kafka. It allows you to navigate topics and search Kafka records."
keywords = ["kafka", "consumer", "avro", "tui", "ratatui"]
categories = [
    "command-line-utilities",
    "gui",
    "development-tools",
]
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[[bin]]
name = "yozf"
path = "src/main.rs"


[dependencies]
tokio = { version = "1", features = ["full"] }
command = { workspace = true }

[features]
default = ["ssl-vendored", "gssapi-vendored"]
ssl-vendored = [
    "command/ssl-vendored"
]
gssapi-vendored = [
    "command/gssapi-vendored"
]